name: Plugin
version: '${project.version}'
main: de.milli.plugin.Plugin
api: 17
commands:
  killall:
  heal:
    description: "Heals all life points to the Player"
  weapon:
  itemsearch:
  itemsearch2: